server:
  address: 'tcp://:9091/'

log:
  level: 'info'

identity_validation:
  reset_password:
    jwt_secret: 'CAMBIAR_ESTO_POR_UN_SECRETO_DE_32_CARACTERES'

authentication_backend:
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: 'deny'
  rules:
    - domain: 'eleccion.sello-legitimo.site'
      policy: 'one_factor'
    - domain: 'preeleccion.sello-legitimo.site'
      policy: 'one_factor'

session:
  secret: 'UN_SECRETO_MUY_LARGO_Y_ALEATORIO_DE_AL_MENOS_64_CARACTERES'
  cookies:
    - name: 'authelia_session'
      domain: 'sello-legitimo.site' # Permite compartir sesión entre subdominios
      authelia_url: 'https://auth.sello-legitimo.site'
      expiration: '1 hour'
      inactivity: '30 minutes'

storage:
  encryption_key: 'OTRA_CLAVE_DE_32_CARACTERES_PARA_CIFRAR_DB'
  local:
    path: '/config/db.sqlite3'

notifier:
  disable_startup_check: true
  filesystem:
    filename: '/config/notification.txt'

identity_providers:
  oidc:
    hmac_secret: 'OTRO_SECRETO_LARGO_DE_64_CARACTERES_PARA_OIDC'
    jwks:
      - key_id: 'sello-legitimo-key'
        algorithm: 'RS256'
        use: 'sig'
        key: |
          -----BEGIN PRIVATE KEY-----
          MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDLXREahav5nRaJ
          ... (tu clave privada actual aquí) ...
          -----END PRIVATE KEY-----
    clients:
      - client_id: 'frontend-configuracion'
        client_name: 'Frontend Eleccion'
        public: true
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://eleccion.sello-legitimo.site/callback'
          - 'https://preeleccion.sello-legitimo.site/callback'
        scopes: ['openid', 'profile', 'email', 'groups']
        grant_types: ['authorization_code']
        response_types: ['code']
        pkce_challenge_method: 'S256'
        consent_mode: 'implicit'