users:
  registraduria:
    displayname: 'Usuario Registraduria'
    ## Contrasena: 12345
    password: '$argon2id$v=19$m=16,t=2,p=1$M2tuVElreXgxU1ZlaHhlTQ$BOisQyGp5bZ/zAuYuQCIMA'
    email: 'registraduria@sello-legitimo.site'
    groups:
      - 'frontend-configuracion'
      - 'frontend-gestion-pre'

  superadmin:
    displayname: 'Superadmin'
    ## Contrasena: 12345
    password: '$argon2id$v=19$m=16,t=2,p=1$M2tuVElreXgxU1ZlaHhlTQ$BOisQyGp5bZ/zAuYuQCIMA'
    email: 'superadmin@sello-legitimo.site'
    groups:
      - 'frontend-configuracion'
      - 'frontend-gestion-pre'