users:
  registraduria:
    displayname: 'Usuario Registraduria'
    ## Contrasena: 12345
    password: '$argon2id$v=19$m=65536,t=3,p=4$UoUfL39JzW1IFH5vdnbBlA$jk56H7YjZvWV7ngdXHURPJo2JdhudNHrX0X7uo+UPnc'
    email: 'registraduria@sello-legitimo.site'
    groups:
      - 'frontend-configuracion'
      - 'frontend-gestion-pre'

  superadmin:
    displayname: 'Superadmin'
    ## Contrasena: 12345
    password: '$argon2id$v=19$m=65536,t=3,p=4$UoUfL39JzW1IFH5vdnbBlA$jk56H7YjZvWV7ngdXHURPJo2JdhudNHrX0X7uo+UPnc'
    email: 'superadmin@sello-legitimo.site'
    groups:
      - 'frontend-configuracion'
      - 'frontend-gestion-pre'