# Si estas leyendo esto, odio el hecho de que 
# este archivo sea tan largo...
#
# La idea seria separarlo en varios archivos mas
# pequeños, pero eso es a futuro.
#                                   - Augusto

services:
    # Gateway
    gateway:
        image: caddy:latest
        ports:
            - 3000:80
        volumes:
            - ./config/caddy:/etc/caddy
        networks:
            - sello-net
        deploy:
            restart_policy:
                condition: any
            placement:
                constraints:
                  - node.role == manager
            resources:
                limits:
                    cpus: "0.50"   # half a CPU core
                    memory: 512M

    # Frontend
    frontend:
        image: ghcr.io/at-sovereign-technologies/sello-legitimo-frontend:latest
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == frontend
    
    # Citizens Query
    citizen-query-service:
        image: ghcr.io/at-sovereign-technologies/citizen-query-service:latest
        environment:
            PORT: 8080
            DB_URL: jdbc:postgresql://citizen-query-postgres:5432/${CITIZENS_QUERY_DB_NAME}
            DB_USER: ${CITIZENS_QUERY_DB_USER}
            DB_PASSWORD: ${CITIZENS_QUERY_DB_PASSWORD}
            REDIS_HOST: citizens-query-redis
            REDIS_PORT: 6379
        networks:
            - sello-net
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices

    citizen-query-postgres:
        image: postgres:14
        environment:
            POSTGRES_DB: ${CITIZENS_QUERY_DB_NAME}
            POSTGRES_USER: ${CITIZENS_QUERY_DB_USER}
            POSTGRES_PASSWORD: ${CITIZENS_QUERY_DB_PASSWORD}
        volumes:
            - citizen_query_data:/var/lib/postgresql/data
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == storage

    citizens-query-redis:
        image: redis:latest
        command: redis-server --appendonly yes
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == storage

    # Results Service
    results-service:
        image: ghcr.io/at-sovereign-technologies/results-service:latest
        environment:
            PORT: 8080
            DB_URL: jdbc:postgresql://results-postgres:5432/${RESULTS_SVC_DB_NAME}
            DB_USER: ${RESULTS_SVC_DB_USER}
            DB_PASSWORD: ${RESULTS_SVC_DB_PASSWORD}
            REDIS_HOST: results-redis
            REDIS_PORT: 6379
        networks:
            - sello-net
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices

    results-postgres:
        image: postgres:14
        environment:
            POSTGRES_DB: ${RESULTS_SVC_DB_NAME}
            POSTGRES_USER: ${RESULTS_SVC_DB_USER}
            POSTGRES_PASSWORD: ${RESULTS_SVC_DB_PASSWORD}
        volumes:
            - results_data:/var/lib/postgresql/data
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == storage

    results-redis:
        image: redis:latest
        command: redis-server --appendonly yes
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == storage

    # Elections Query
    elections-query-service:
        image: ghcr.io/at-sovereign-technologies/election-query-service:latest
        environment:
            PORT: 8080
            DB_URL: jdbc:postgresql://elections-query-postgres:5432/${ELECTIONS_QUERY_DB_NAME}
            DB_USER: ${ELECTIONS_QUERY_DB_USER}
            DB_PASSWORD: ${ELECTIONS_QUERY_DB_PASSWORD}
            REDIS_HOST: elections-query-redis
            REDIS_PORT: 6379
        networks:
            - sello-net
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices

    elections-query-postgres:
        image: postgres:14
        environment:
            POSTGRES_DB: ${ELECTIONS_QUERY_DB_NAME}
            POSTGRES_USER: ${ELECTIONS_QUERY_DB_USER}
            POSTGRES_PASSWORD: ${ELECTIONS_QUERY_DB_PASSWORD}
        volumes:
            - elections_query_data:/var/lib/postgresql/data
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == storage

    elections-query-redis:
        image: redis:latest
        command: redis-server --appendonly yes
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == storage

    # Transparency Query
    transparency-service:
        image: ghcr.io/at-sovereign-technologies/transparency-service:latest
        environment:
            PORT: 8080
            DB_URL: jdbc:postgresql://transparency-postgres:5432/${TRANSPARENCY_SVC_DB_NAME}
            DB_USER: ${TRANSPARENCY_SVC_DB_USER}
            DB_PASSWORD: ${TRANSPARENCY_SVC_DB_PASSWORD}
            REDIS_HOST: transparency-redis
            REDIS_PORT: 6379
        networks:
            - sello-net
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices

    transparency-postgres:
        image: postgres:14
        environment:
            POSTGRES_DB: ${TRANSPARENCY_SVC_DB_NAME}
            POSTGRES_USER: ${TRANSPARENCY_SVC_DB_USER}
            POSTGRES_PASSWORD: ${TRANSPARENCY_SVC_DB_PASSWORD}
        volumes:
            - transparency_data:/var/lib/postgresql/data
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == storage

    transparency-redis:
        image: redis:latest
        command: redis-server --appendonly yes
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == storage

    election-conf-frotnend:
        image: ghcr.io/at-sovereign-technologies/frontend-configuracionelecciones:latest
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == frontend

    election-conf-service:
        image: ghcr.io/at-sovereign-technologies/configuracioneleccion-service:latest
        environment:
            PORT: 8081
            DB_URL: jdbc:postgresql://election-conf-postgres:5432/${ELECTION_CONF_SVC_DB_NAME}
            DB_USERNAME: ${ELECTION_CONF_SVC_DB_USER}
            DB_PASSWORD: ${ELECTION_CONF_SVC_DB_PASSWORD}
        networks:
            - sello-net
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices

    election-conf-postgres:
        image: postgres:14
        environment:
            POSTGRES_DB: ${ELECTION_CONF_SVC_DB_NAME}
            POSTGRES_USER: ${ELECTION_CONF_SVC_DB_USER}
            POSTGRES_PASSWORD: ${ELECTION_CONF_SVC_DB_PASSWORD}
        volumes:
            - election_conf_data:/var/lib/postgresql/data
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == storage

    preelectoral-frotnend:
        image: ghcr.io/at-sovereign-technologies/frontend-gestionpreelectoral:latest
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == frontend

    preelectoral-service:
        image: ghcr.io/at-sovereign-technologies/gestionpreelectoral-service:latest
        environment:
            PUERTO: 8080
            DB_URL: jdbc:postgresql://preelectoral-postgres:5432/${PREELECTORAL_SVC_DB_NAME}
            DB_USUARIO: ${PREELECTORAL_SVC_DB_USER}
            DB_CLAVE: ${PREELECTORAL_SVC_DB_PASSWORD}
        networks:
            - sello-net
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices

    preelectoral-postgres:
        image: postgres:14
        environment:
            POSTGRES_DB: ${PREELECTORAL_SVC_DB_NAME}
            POSTGRES_USER: ${PREELECTORAL_SVC_DB_USER}
            POSTGRES_PASSWORD: ${PREELECTORAL_SVC_DB_PASSWORD}
        volumes:
            - preelectoral_data:/var/lib/postgresql/data
        networks:
            - sello-net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == storage

volumes:
    citizen_query_data:
    results_data:
    elections_query_data:
    transparency_data:
    election_conf_data:
    preelectoral_data:

networks:
  sello-net:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: "1400"