# Citizens Service
@elecciones_match {
    path /api/elecciones /api/elecciones/*
}

handle @elecciones_match {
    reverse_proxy tasks.election-conf-service:8081
}

# Catch all to prevent endpoint issues - Augusto
handle /api/* {
    respond "Forbidden" 403
} 