# Configuracion Electoral
@elecciones_match {
    path /api/elecciones /api/elecciones/*
}

handle @elecciones_match {
    # Service doesn't provide a way to actually change this port.
    # This is an issue and should be fixed. - Augusto
    reverse_proxy tasks.election-conf-service:8081 
}

# Gestion Preelectoral
@preelectoral_match {
    path /api/censo /api/censo/* /api/candidaturas /api/candidaturas/*
}

handle @preelectoral_match {
    reverse_proxy preelectoral-service:8080
}

# Catch all to prevent endpoint issues - Augusto
handle /api/* {
    respond "Forbidden" 403
} 