eleccion.sello-legitimo.site {
    import requires_auth

    handle /api/* {
        reverse_proxy tasks.election-conf-service:8081 
    }

    handle {
        reverse_proxy preelectoral-frontend:80
    }
}