http://preeleccion.sello-legitimo.site {
    import requires_auth

    handle /api/* {
        reverse_proxy preelectoral-service:8080
    }

    handle {
        reverse_proxy election-conf-frontend:80
    }
}