preeleccion.sello-legitimo.site {
    tls internal

    handle /api/* {
        reverse_proxy sr-pre-elections-service:8080
    }

    handle {
        reverse_proxy sr-pre-elections-frontend:80
    }
}