services:
    sr-elections-frontend:
        image: ghcr.io/at-sovereign-technologies/frontend-configuracionelecciones:latest
        networks:
            - sello-net-prod
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == frontend
                    - node.labels.env == prod

    sr-pre-election-frontend:
        image: ghcr.io/at-sovereign-technologies/frontend-gestionpreelectoral:latest
        networks:
            - sello-net-prod
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == frontend
                    - node.labels.env == prod

    sr-elections-service:
        image: ghcr.io/at-sovereign-technologies/configuracioneleccion-service:latest
        environment:
            PORT: 8081
            DB_URL: jdbc:postgresql://postgres:5432/${ELECTION_CONF_SVC_DB_NAME}
            DB_USERNAME: ${ELECTION_CONF_SVC_DB_USER}
            DB_PASSWORD: ${ELECTION_CONF_SVC_DB_PASSWORD}
        networks:
            - sello-net-prod
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices
                    - node.labels.env == prod

    sr-pre-election-service:
        image: ghcr.io/at-sovereign-technologies/gestionpreelectoral-service:latest
        environment:
            PUERTO: 8080
            DB_URL: jdbc:postgresql://postgres:5432/${PREELECTORAL_SVC_DB_NAME}
            DB_USUARIO: ${PREELECTORAL_SVC_DB_USER}
            DB_CLAVE: ${PREELECTORAL_SVC_DB_PASSWORD}
        networks:
            - sello-net-prod
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices
                    - node.labels.env == prod