services:
    sc-frontend:
        image: ghcr.io/at-sovereign-technologies/sello-legitimo-frontend:devel
        networks:
            - sello-net-qa
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == frontend
                    - node.labels.env == qa

    sc-elections-service:
        image: ghcr.io/at-sovereign-technologies/election-query-service:devel
        environment:
            PORT: 8080
            DB_URL: jdbc:postgresql://postgres:5432/${SC_ELECTIONS_DB_NAME}
            DB_USER: ${SC_ELECTIONS_DB_USER}
            DB_PASSWORD: ${SC_ELECTIONS_DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: 2
        networks:
            - sello-net-qa
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices
                    - node.labels.env == qa

    sc-citizens-service:
        image: ghcr.io/at-sovereign-technologies/citizen-query-service:devel
        environment:
            PORT: 8080
            DB_URL: jdbc:postgresql://postgres:5432/${SC_CITIZENS_DB_NAME}
            DB_USER: ${SC_CITIZENS_DB_USER}
            DB_PASSWORD: ${SC_CITIZENS_DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: 0
        networks:
            - sello-net-qa
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices
                    - node.labels.env == qa

    sc-results-service:
        image: ghcr.io/at-sovereign-technologies/results-service:devel
        environment:
            PORT: 8080
            DB_URL: jdbc:postgresql://postgres:5432/${SC_RESULTS_DB_NAME}
            DB_USER: ${SC_RESULTS_DB_USER}
            DB_PASSWORD: ${SC_RESULTS_DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: 1
        networks:
            - sello-net-qa
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices
                    - node.labels.env == qa

    sc-transparency-service:
        image: ghcr.io/at-sovereign-technologies/transparency-service:devel
        environment:
            PORT: 8080
            DB_URL: jdbc:postgresql://postgres:5432/${SC_TRANSPARENCY_DB_NAME}
            DB_USER: ${SC_TRANSPARENCY_DB_USER}
            DB_PASSWORD: ${SC_TRANSPARENCY_DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: 3
        networks:
            - sello-net-qa
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices
                    - node.labels.env == qa
