services:
    sr-elections-service:
        image: ghcr.io/at-sovereign-technologies/configuracioneleccion-service:devel
        environment:
            PORT: 8080
            DB_URL: jdbc:postgresql://postgres:5432/${SR_ELECTIONS_DB_NAME}
            DB_USERNAME: ${SR_ELECTIONS_DB_USER}
            DB_PASSWORD: ${SR_ELECTIONS_DB_PASSWORD}
            GRPC_PORT: 9090
        networks:
            - sello-net-qa
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices
                    - node.labels.env == qa

    sr-pre-elections-service:
        image: ghcr.io/at-sovereign-technologies/gestionpreelectoral-service:devel
        environment:
            PUERTO: 8080
            DB_URL: jdbc:postgresql://postgres:5432/${SR_PRE_ELECTIONS_DB_NAME}
            DB_USUARIO: ${SR_PRE_ELECTIONS_DB_USER}
            DB_CLAVE: ${SR_PRE_ELECTIONS_DB_PASSWORD}
        networks:
            - sello-net-qa
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices
                    - node.labels.env == qa
    
    sr-mock-jury-service:
        image: ghcr.io/at-sovereign-technologies/mockjurados-service:devel
        environment:
            PUERTO: 8080
            ELECCIONES_GRPC_HOST: sr-elections-service
            ELECCIONES_GRPC_PORT: 9090
            CENSO_SERVICE_URL: /
        networks:
            - sello-net-qa
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices
                    - node.labels.env == qa
                    
    sr-scrutiny-service:
        image: ghcr.io/at-sovereign-technologies/scrutiny-service:devel
        environment:
            PORT: 8080
            DB_URL: jdbc:postgresql://postgres:5432/${SR_SCRUTINY_DB_NAME}
            DB_USER: ${SR_SCRUTINY_DB_USER}
            DB_PASSWORD: ${SR_SCRUTINY_DB_PASSWORD}
        networks:
            - sello-net-qa
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices
                    - node.labels.env == qa

    fraude-service:
        image: ghcr.io/at-sovereign-technologies/fraude-service:devel
        environment:
            PORT: 8084
            FRAUDE_DB_HOST: postgres
            FRAUDE_DB_PORT: 5432
            FRAUDE_DB_NAME: ${FRAUDE_DB_NAME}
            FRAUDE_DB_USER: ${FRAUDE_DB_USER}
            FRAUDE_DB_PASSWORD: ${FRAUDE_DB_PASSWORD}
        networks:
            - sello-net-qa
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.labels.type == microservices
                    - node.labels.env == qa
